baseURL = 'https://peterkorteweg.github.io'
defaultContentLanguage = "en"
languageCode = 'en-us'

title = 'Peter Korteweg'

theme = 'gokarna'

[menu]
  [[menu.main]]
    identifier = 'photos'
    url = '/photos/'  
	name = 'Photos'
    #pre = "<span data-feather='book-open'></span>"    
    weight = 1

  [[menu.main]]
    identifier = 'puzzles'
    url = '/puzzle/'
	name = 'Puzzles'
    weight = 2
	
  [[menu.main]]
    identifier = 'publications'
    url = '/publications/'
	name = 'Publications'
    #pre = "<span data-feather='pen-tool'></span>"    
    weight = 3	
	
[params]
  footer = 'Peter Korteweg'
  
  description = 'I am a quant who collects photobooks and mathematical puzzles.'
  
  avatarURL = '/images/CoitTower.jpg'
  AvatarAltText = ''
  avatarSize = 'size-m'
  
  accentColor = '#0048ba'  # Accent color is displayed when you hover over <a> tags
  
  dateFormat = 'January 2006'
    
  metaKeywords = ["peter korteweg"] # Keywords relevant for SEO
      
  socialIcons = [
      {name = 'github', url = 'https://github.com/peterkorteweg'},
	  {name = 'rss', url = 'https://www.goodreads.com/review/list/171184162-peter?order=d&shelf=quant&sort=avg_rating'},      
	  {name = 'linkedin', url = 'https://www.linkedin.com/in/peterkorteweg/'},      
    ]
	
  [params.hiddenTags]
  tagsHidePostDate = ["puzzles"]

  [params.hidden]
  tagsPostDate = ["puzzles"]

customHeadHTML = '''
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css" integrity="sha384-Xi8rHCmBmhbuyyhbI88391ZKP2dmfnOl4rT9ZfRI7mLTdk1wblIUnrIq35nqwEvC" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js" integrity="sha384-X/XCfMm41VSsqRNQgDerQczD69XqmjOOOwYQvr/uuC+j4OPoNhVgjdGFwhvN02Ja" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js" integrity="sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR" crossorigin="anonymous"></script>
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        renderMathInElement(document.body, {
          // customised options
          // • auto-render specific keys, e.g.:
          delimiters: [
            {left: '$$', right: '$$', display: true},
            {left: '$', right: '$', display: false},
          ],
          // • rendering keys, e.g.:
          throwOnError : false
        });
      });
    </script>
  '''	